
# Read about DVC pipeline configuration (https://dvc.org/doc/user-guide/project-structure/dvcyaml-files#stages)
# to customize your stages even more
stages:
  train:
    cmd: python experiments/07-ESN-STDP/nb&flows/03-Forecast-Lorenz-perf_wrt_signal_shift.py
    deps:
      - experiments/07-ESN-STDP/nb&flows/03-Forecast-Lorenz-perf_wrt_signal_shift.py