[tool.poetry]
name = "research-snn-vs-ann-in-rl"
version = "0.1.0"
description = "Comparison of economics of choices between SNN and ANN in RL"
authors = ["gianfa <gian.angelini@hotmail.com>"]

[tool.poetry.dependencies]
python = ">=3.9,<3.9.7 || >3.9.7,<4.0"

numpy = "^1.23.2"
pandas = "^1.4.4"
matplotlib = "^3.5.3"
snntorch = "^0.5.3"
torchvision = "^0.13.1"

[tool.poetry.dev-dependencies]
flake8 = "^5.0.4"
jupyter = "^1.0.0"
black = "^22.8.0"
streamlit= "*"
watchdog="*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
